### ISSUE TITLE
CChatAppLayer

### ISSUE THREAD

**Issue by BiteSnail** [BiteSnail/FileTransferWithMFC#3]
### 목표
CChat App Layer의 전체적인 수정 및 기능 추가

### 프로토타입 헤더
해당 헤더를 바탕으로 소스코드 작성 바람. 만약 구현 중 변경해야 할 사항이 있다면 이슈 바람.
```C++
#define CHAT_HEADER_SIZE 4
#define CHAR_DATA_MAX_SIZE 1496

class CChatAppLayer : public CBaseLayer
{
private:
	inline void		ResetHeader();
	CObject* mp_Dlg;

public:
	BOOL			Receive(unsigned char* ppayload); 
	//1. 만약 메시지 type이 0x00인 경우 그대로 dlg layer로 전송
	//2. 만약 메시지 type이 0x01인 경우 버퍼에 저장
	//3. 만약 메시지 type이 0x02인 경우 버퍼에 저장된 데이터 dlg layer로 전송
	BOOL			Send(unsigned char* ppayload, int nlength); 
        //1. 입력된 데이터의 길이를 측정
        //2. 입력된 데이터의 길이가 1496byte를 초과하면 데이터를 1496byte단위로 쪼갠다.
        //3. 만약 쪼갰다면 메시지 타입을 0x01로 바꿔서 전송(unused를 sequence로 사용)
	//4. 쪼갠 메시지의 마지막 데이터를 메시지 타입을 0x02로 바꿔서 전송

	CChatAppLayer(char* pName);
	virtual ~CChatAppLayer();

	typedef struct _CHAT_APP
	{
	    unsigned short capp_totlen ; // 메시지 총 길이
	    unsigned char capp_type ; // 메시지 타입
	    unsigned char capp_unused ; // 우선 사용 안함
	    unsigned char capp_data[ MAX_APP_DATA ] ;
	} CHAT_APP, *LPCHAT_APP ;

protected:
	CHAT_APP_HEADER		m_sHeader;

	enum { //unused를 sequence처럼 사용하는 것 고려 
		DATA_TYPE_DONT = 0x00,
		DATA_TYPE_CONT = 0x01,
		DATA_TYPE_END = 0x02
	};
};
```

**Comment by poeo1877** [comment]
fragment 상황도 고려해서 CChatAppLayer 코드 작성하였습니다. 아직 IPC 만 사용하던 코드는 정리 안되었으니 참고하시고 확인 부탁드립니다.

**Comment by BiteSnail** [comment]
감사합니다!
코드 확인 중입니다. 
그런데 ipc2019에서 유일하게 생성한 객체라고 되어있는 부분은 무엇 때문에 작성하신건지 궁금합니다

**Comment by poeo1877** [comment]
main branch에서 작성된 code인데 아마 IPC 에서 사용하던 코드인 것 같습니다.

**Comment by BiteSnail** [comment]
아 죄송 ㅋㅋㅋㅋㅋ
diff에 걸려서 뭔가 했더니 빈줄 생성 및 지움이네요 
감사합니다

**Comment by poeo1877** [comment]
문제 없으면 IPC에서 만 사용하는 코드들 정리하겠습니다.

**Comment by BiteSnail** [comment]
넵 풀리퀘 해주십쇼

**Comment by poeo1877** [comment]
### 함수 역할
![image](https://user-images.githubusercontent.com/67182280/194847364-12cecf77-1dd8-4894-9bdb-dafd756b5ce6.png)
#### add_after( )
인자로 받은 구조체 포인터 뒤에 새 Node 생성 후 fragement 값을 넣는 함수
#### seq_compare( )
새로운 fragment Message와 연결리스트 노드의 capp_sequence 값을 비교해 더 작은 값을 찾는 함수
#### add( )
연결리스트에서 해당 fragment가 위치할 부분을 찾아주는 함수
#### make_frame( )
하위 레이어(Ethernet Layer)로 보낼 frame을 만드는 함수
#### deleteList( )
연결리스트로 사용한 메모리 반환하는 함수

### 함수 설명
![image](https://user-images.githubusercontent.com/67182280/194849421-422976b1-8966-4643-9a66-d7ff86b23fa3.png)
nlength가 1496보다 작으면 단편화 작업 없이 하위 레이어로 보낸다. 그 외에 경우에는 단편화를 하여 하위 레이어로 보낸다.
단편화 구분은 capp_type 값이...
0x00: 단편화 없음, 0x01: 단편화 시작, 0x02: 단편화 중간부분, 0x03: 단편화 를 의미한다.

![image](https://user-images.githubusercontent.com/67182280/194850564-d4ba41fc-ac1f-40a6-a15d-56e9cc42e8c1.png)
전달 받은 Message Header에 capp_type를 보고 단편화 구분을 한다.
만약 단편화 된 경우 단편화 된 순서에 맞게 연결리스트에서 정리한 후 버퍼에 Message data를 넣는다. 이후 버퍼 값을 상위 레이어(File & Chat Dlg)로 보낸다.

**Comment by BiteSnail** [comment]
#16 으로 해당 구현 종료합니다.
